FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS initial_build

WORKDIR /app

COPY *.csproj ./

RUN dotnet restore

COPY . ./

RUN dotnet publish -c release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

COPY --from=initial_build /app/out ./

ENTRYPOINT ["dotnet", "AuthenticationService.dll"]

