# Stage 1
FROM node:8.11.2-alpine as node

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build -- --output-path=./dist/out

# Stage 2
FROM nginx:1.13.12-alpine

COPY --from=node /app/dist/out /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf